### ISSUE TITLE
Tracking: PCB Board Design & Fabrication

### ISSUE THREAD

**Issue by arandell93** [LakeMaps/Dartmouth#4]
These are listed in order of priority.
Each board should have a separate issue created for it to discuss relevant things, but progress will be tracked here and dates will be assigned.
### Radio Module Board (#2)
- [ ] Circuit Design & Schematic [August 3]
- [ ] Component Selection [July 28]
- [ ] PCB Layout [August 3]
- [ ] PCB Ordering [August 5]
- [ ] PCB Assembly
- [ ] Testing
### Motherboard (Dartmouth) (#1)
- [ ] Circuit Design & Schematic [August 3]
- [ ] Component Selection [August 3]
- [ ] PCB Layout
- [ ] PCB Ordering
- [ ] PCB Assembly
- [ ] Testing
### GPS Daughterboard
- [ ] Circuit Design & Schematic
- [ ] Component Selection
- [ ] PCB Layout
- [ ] PCB Ordering
- [ ] PCB Assembly
- [ ] Testing
### Sonar Daughterboard
- [ ] Circuit Design & Schematic
- [ ] Component Selection
- [ ] PCB Layout
- [ ] PCB Ordering
- [ ] PCB Assembly
- [ ] Testing
### Motor Controller Daughterboard
- [ ] Circuit Design & Schematic
- [ ] Component Selection
- [ ] PCB Layout
- [ ] PCB Ordering
- [ ] PCB Assembly
- [ ] Testing
